services:
  app:
    build: .
    volumes:
      - /home/user/app/target
      - .:/home/user/app
    depends_on:
      - postgre
    env_file:
      - .env
    command: bash
    tty: true

  postgre:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/sql.sql:/docker-entrypoint-initdb.d/sql.sql